# -*- coding: utf-8 -*-

MAX_NUMBER_OF_PROMOTED_EVENTS = 8
MAX_NUMBER_OF_PROMOTED_NEWS = 10
MAX_NUMBER_OF_PROMOTED_ARTICLES = 4
MAX_NUMBER_OF_PROMOTED_ENTITIES = 3

DEFAULT_PER_PAGE = 10
NUMBER_OF_PER_PAGE_OPTIONS = 10

MAX_NUMBER_OF_SIMILAR_ENTITIES = 4
MAX_NUMBER_OF_LATEST_NEWS = 5
